"""Shell completion scripts generated from the parser.

The scripts are produced on demand rather than committed, so they cannot fall
behind the parser. Service names are completed by calling back into
`LocalSM completion services`, which keeps the scripts free of any dependency
on jq or python.
"""

from __future__ import annotations

from .cli_model import Command

SHELLS = ("zsh", "bash")


def _service_commands(root: Command) -> list[str]:
    """Commands whose first positional names a service."""
    names = []
    for command in root.walk():
        if command.positionals and command.positionals[0].metavar.lower() == "service":
            names.append(" ".join(command.path))
    return sorted(names)


def _flags(command: Command) -> list[str]:
    flags = ["--json", "--quiet", "--help"]
    for option in command.options:
        flags.extend(option.flags)
    return sorted(set(flags))


def render_zsh(root: Command) -> str:
    top = [item for item in root.subcommands]
    lines = [
        "#compdef LocalSM",
        "# Generated by `LocalSM completion zsh`; regenerate after upgrading.",
        "",
        "_LocalSM_services() {",
        "  local -a names",
        '  names=(${(f)"$(LocalSM completion services 2>/dev/null)"})',
        "  _describe -t services service names",
        "}",
        "",
        "_LocalSM() {",
        "  local curcontext=$curcontext state line",
        "  local -a commands",
        "  commands=(",
    ]
    for command in top:
        description = (command.help or "").replace("'", "").replace(":", " -")
        lines.append(f"    '{command.name}:{description}'")
    lines += [
        "  )",
        "  _arguments -C \\",
        "    '--json[emit machine-readable JSON]' \\",
        "    '--quiet[suppress informational output]' \\",
        "    '(- *)--version[show the LocalSM version]' \\",
        "    '(- *)'{-h,--help}'[show help]' \\",
        "    '1: :->command' \\",
        "    '*:: :->argument' && return 0",
        "",
        "  case $state in",
        "    command) _describe -t commands 'LocalSM command' commands ;;",
        "    argument)",
        "      case $words[1] in",
    ]
    service_commands = set(_service_commands(root))
    for command in top:
        clauses = []
        if command.subcommands:
            nested = " ".join(f"'{item.name}:{(item.help or '').replace(chr(39), '')}'" for item in command.subcommands)
            clauses.append(f"local -a sub; sub=({nested}); _describe -t commands '{command.name} command' sub")
        elif command.name in service_commands:
            clauses.append("_LocalSM_services")
        flags = " ".join(_flags(command))
        clauses.append(f"compadd -- {flags}" if flags else ":")
        lines.append(f"        {command.name}) {'; '.join(clauses)} ;;")
    lines += [
        "      esac",
        "      ;;",
        "  esac",
        "}",
        "",
        '_LocalSM "$@"',
        "",
    ]
    return "\n".join(lines)


def render_bash(root: Command) -> str:
    top = [item.name for item in root.subcommands]
    service_commands = _service_commands(root)
    lines = [
        "# Generated by `LocalSM completion bash`; regenerate after upgrading.",
        "# Load with: source <(LocalSM completion bash)",
        "",
        "_LocalSM() {",
        "  local current previous command",
        '  current="${COMP_WORDS[COMP_CWORD]}"',
        '  previous="${COMP_WORDS[COMP_CWORD-1]}"',
        '  command="${COMP_WORDS[1]}"',
        "",
        f'  local commands="{" ".join(top)}"',
        f'  local service_commands="{" ".join(name for name in service_commands if " " not in name)}"',
        "",
        '  if [ "$COMP_CWORD" -eq 1 ]; then',
        '    COMPREPLY=($(compgen -W "$commands --json --quiet --version --help" -- "$current"))',
        "    return",
        "  fi",
        "",
        '  case "$command" in',
    ]
    for command in root.subcommands:
        words = list(_flags(command))
        words.extend(item.name for item in command.subcommands)
        joined = " ".join(sorted(set(words)))
        lines.append(f'    {command.name}) COMPREPLY=($(compgen -W "{joined}" -- "$current")) ;;')
    lines += [
        "  esac",
        "",
        "  # Offer service names for the commands whose first argument is one.",
        '  if [ "$COMP_CWORD" -eq 2 ] && [[ " $service_commands " == *" $command "* ]]; then',
        '    COMPREPLY+=($(compgen -W "$(LocalSM completion services 2>/dev/null)" -- "$current"))',
        "  fi",
        "}",
        "",
        "complete -F _LocalSM LocalSM",
        "",
    ]
    return "\n".join(lines)


def render(shell: str, root: Command) -> str:
    if shell == "zsh":
        return render_zsh(root)
    if shell == "bash":
        return render_bash(root)
    raise ValueError(f"unsupported shell {shell!r}; choose from {', '.join(SHELLS)}")
