"""Render the CLI reference markdown from the parser, in either language."""

from __future__ import annotations

from .cli_model import Command

LANGUAGES = ("zh", "en")

_BANNER = (
    "<!-- Generated by scripts/gen_cli_reference.py; run `make docs-cli` after\n"
    "changing the parser in src/localsm/cli.py. Do not edit by hand. -->\n"
)

_INTRO = {
    "zh": """# CLI 参考

LocalSM 的每条命令都接受全局 `--json` 与 `--quiet`，放在子命令前后均可。
输出形态与退出码约定见 [cli-contract.md](cli-contract.md)。

```sh
# 补全脚本（一次性写入即可）
LocalSM completion zsh > "${fpath[1]}/_LocalSM"
source <(LocalSM completion bash)
```
""",
    "en": """# CLI reference

Every LocalSM command accepts the global `--json` and `--quiet` flags, before
or after the subcommand. See [cli-contract.md](cli-contract.md) for the output
shapes and exit codes.

```sh
# Shell completion, written once
LocalSM completion zsh > "${fpath[1]}/_LocalSM"
source <(LocalSM completion bash)
```
""",
}

_TABLE_HEADER = {
    "zh": ("| 参数 | 说明 |", "| --- | --- |"),
    "en": ("| Argument | Description |", "| --- | --- |"),
}

_CHOICES_LABEL = {"zh": "取值：", "en": "One of: "}


def _argument_rows(command: Command, lang: str) -> list[str]:
    rows = []
    for argument in (*command.positionals, *command.options):
        name = ", ".join(f"`{flag}`" for flag in argument.flags) if argument.flags else f"`{argument.metavar}`"
        detail = argument.help or ""
        if argument.choices:
            choices = ", ".join(f"`{choice}`" for choice in argument.choices)
            detail = f"{detail} {_CHOICES_LABEL[lang]}{choices}".strip()
        rows.append(f"| {name} | {detail} |")
    return rows


def _section(command: Command, level: int, lang: str) -> list[str]:
    lines = [f"{'#' * level} {command.full_name}", ""]
    if command.help:
        lines += [command.help, ""]
    lines += ["```text", command.signature(), "```", ""]
    rows = _argument_rows(command, lang)
    if rows:
        lines += [*_TABLE_HEADER[lang], *rows, ""]
    for child in command.subcommands:
        lines += _section(child, level + 1, lang)
    return lines


def render_markdown(root: Command, lang: str = "zh") -> str:
    if lang not in LANGUAGES:
        raise ValueError(f"unsupported language {lang!r}; choose from {', '.join(LANGUAGES)}")
    parts = [f"{_BANNER}\n{_INTRO[lang]}"]
    for command in root.subcommands:
        parts.append("\n".join(_section(command, 2, lang)))
    return "\n".join(parts).rstrip() + "\n"
